# Generated by Django 2.0.3 on 2018-06-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180627_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='one', unique=True),
            preserve_default=False,
        ),
    ]
