# Generated by Django 2.0.3 on 2018-06-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='name', unique=True),
            preserve_default=False,
        ),
    ]
